# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x08\x63onfigpb\"\xba\x01\n\rConfiguration\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\x05\x12\t\n\x01n\x18\x03 \x01(\x05\x12\t\n\x01\x66\x18\x04 \x01(\x05\x12\r\n\x05\x64\x65lta\x18\x05 \x01(\x05\x12\x10\n\x08\x64\x65ltaBar\x18\x06 \x01(\x05\x12\x12\n\nblsKeyPath\x18\x07 \x01(\t\x12\n\n\x02pk\x18\x08 \x01(\t\x12\n\n\x02\x63k\x18\t \x01(\t\x12\x0c\n\x04sign\x18\n \x01(\x08\x12\x1d\n\x05peers\x18\x0b \x03(\x0b\x32\x0e.configpb.Peer\"0\n\x04Peer\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12\x0e\n\x06\x63lient\x18\x03 \x01(\tB\x0cZ\n./configpbb\x06proto3')



_CONFIGURATION = DESCRIPTOR.message_types_by_name['Configuration']
_PEER = DESCRIPTOR.message_types_by_name['Peer']
Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATION,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configpb.Configuration)
  })
_sym_db.RegisterMessage(Configuration)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), {
  'DESCRIPTOR' : _PEER,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configpb.Peer)
  })
_sym_db.RegisterMessage(Peer)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./configpb'
  _CONFIGURATION._serialized_start=27
  _CONFIGURATION._serialized_end=213
  _PEER._serialized_start=215
  _PEER._serialized_end=263
# @@protoc_insertion_point(module_scope)
